name: noise_meter_example
description: Example app for the noise_meter package.
publish_to: none
version: 5.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  noise_meter:
    path: ../

  cupertino_icons: ^1.0.2
  permission_handler: ^11.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
