name: noise_meter
description: A Flutter plugin for collecting noise from the phone's microphone.
version: 5.0.2
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_streamer: 
    git:
      url: https://github.com/ranipanimisha94/audio_stream.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
